// Generated by Wrangler on Mon Jun 17 2024 19:11:17 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	MY_VAR: "my-var-value";
	MY_VAR_A: "my-var-a";
	MY_JSON_VAR: {"test":true};
	MY_SERVICE_A: Fetcher;
	MY_SERVICE_B: Fetcher;
	MY_RPC: Fetcher;
}
